In [2]:
import pandas as pd
#melt()
#example
wide_df = pd.DataFrame(
    {
        'Store' : ['North','South','East'],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000]
    }
)
wide_df

   Store  2021  2022  2023
0  North  1200  1500  1400
1  South   800   900   850
2   East   900  1100  1000

In [3]:
#unpivot pd.melt()
long_df = pd.melt(
    wide_df,#data
    id_vars=['Store'], #columns
    value_vars=['2021','2022'], #colum to melt
    var_name='year', #new column
    value_name='sales' #new column

)
long_df

   Store  year  sales
0  North  2021   1200
1  South  2021    800
2   East  2021    900
3  North  2022   1500
4  South  2022    900
5   East  2022   1100

In [4]:
long_df.to_csv("data.csv")

In [5]:
data = pd.DataFrame(
    {
        'Store' : ['North','South','East'],
        'Product':['Laptop','Mouse','Keyboard'],
        '2021':[1200,800,900],
        '2022':[1500,900,1100],
        '2023':[1400,850,1000],
        'price_day1':[120,450,650],
        'price_day2':[560,890,780]
    }
)
data

   Store   Product  2021  2022  2023  price_day1  price_day2
0  North    Laptop  1200  1500  1400         120         560
1  South     Mouse   800   900   850         450         890
2   East  Keyboard   900  1100  1000         650         780

In [6]:
long_df=pd.melt(
   data,
   id_vars=['Product'],
   value_vars=['price_day1','price_day2'],
   var_name='price day',
   value_name='price'
)
long_df

    Product   price day  price
0    Laptop  price_day1    120
1     Mouse  price_day1    450
2  Keyboard  price_day1    650
3    Laptop  price_day2    560
4     Mouse  price_day2    890
5  Keyboard  price_day2    780

In [7]:
#MELT ALL
long_all = pd.melt(
    wide_df,
    id_vars=['Store'],
    var_name='Year',
    value_name='Sales'
    )
long_all

   Store  Year  Sales
0  North  2021   1200
1  South  2021    800
2   East  2021    900
3  North  2022   1500
4  South  2022    900
5   East  2022   1100
6  North  2023   1400
7  South  2023    850
8   East  2023   1000

In [8]:
long_all1 = pd.melt(
    data,
    id_vars=['Product'],
    var_name='year',
    value_name='sales'
)
long_all1

     Product        year  sales
0     Laptop       Store  North
1      Mouse       Store  South
2   Keyboard       Store   East
3     Laptop        2021   1200
4      Mouse        2021    800
5   Keyboard        2021    900
6     Laptop        2022   1500
7      Mouse        2022    900
8   Keyboard        2022   1100
9     Laptop        2023   1400
10     Mouse        2023    850
11  Keyboard        2023   1000
12    Laptop  price_day1    120
13     Mouse  price_day1    450
14  Keyboard  price_day1    650
15    Laptop  price_day2    560
16     Mouse  price_day2    890
17  Keyboard  price_day2    780

In [9]:
wide_df['Manager']=['shrenik','rupali','ashok']
long_df = pd.melt(
    wide_df,#data
    id_vars=['Store','Manager'], #columns
    value_vars=['2021','2022','2023'], #colum to melt
    var_name='year', #new column
    value_name='sales' #new column

)
long_df

   Store  Manager  year  sales
0  North  shrenik  2021   1200
1  South   rupali  2021    800
2   East    ashok  2021    900
3  North  shrenik  2022   1500
4  South   rupali  2022    900
5   East    ashok  2022   1100
6  North  shrenik  2023   1400
7  South   rupali  2023    850
8   East    ashok  2023   1000

In [15]:
#MELT ALL
long_all = pd.melt(
    data,
    id_vars=['Store','Product'],
    var_name='Year',
    value_name='Sales'
    )
long_all

    Store   Product        Year  Sales
0   North    Laptop        2021   1200
1   South     Mouse        2021    800
2    East  Keyboard        2021    900
3   North    Laptop        2022   1500
4   South     Mouse        2022    900
5    East  Keyboard        2022   1100
6   North    Laptop        2023   1400
7   South     Mouse        2023    850
8    East  Keyboard        2023   1000
9   North    Laptop  price_day1    120
10  South     Mouse  price_day1    450
11   East  Keyboard  price_day1    650
12  North    Laptop  price_day2    560
13  South     Mouse  price_day2    890
14   East  Keyboard  price_day2    780

In [17]:
scores_wide = pd.DataFrame({
    'Student': ['Ali', 'Beth', 'Cathy'],
    'Math': [85, 90, 78],
    'Science': [88, 92, 80],
    'English': [90, 85, 88]
})
scores_wide

  Student  Math  Science  English
0     Ali    85       88       90
1    Beth    90       92       85
2   Cathy    78       80       88

In [18]:
#output
#student | Subject | Score
Student_all=  pd.melt(
    scores_wide,
    id_vars=['Student'],
    var_name='Subject',
    value_name='Score'

)
Student_all

  Student  Subject  Score
0     Ali     Math     85
1    Beth     Math     90
2   Cathy     Math     78
3     Ali  Science     88
4    Beth  Science     92
5   Cathy  Science     80
6     Ali  English     90
7    Beth  English     85
8   Cathy  English     88

In [20]:
#average score per subject 
Student_all.groupby('Subject')['Score'].mean().round(2)

Subject
English    87.67
Math       84.33
Science    86.67
Name: Score, dtype: float64